
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
edition = "2021"
name = "math-expresion-evaluator"
version = "0.1.0"

[dependencies]
clap = {version = "3.2.12", features = ["derive"]}
lazy_static = "1.4.0"
regex = "1.6.0"
